### ISSUE TITLE
Do not include link to Twitter image gallery when signature set to false

### ISSUE THREAD

**Issue by Cknight70** [robertoszek/pleroma-bot#56]
Hello again. I noticed that when posting an image from Twitter to Pleroma, the bot will also post a link to the Tweet's image gallery eg:  https://twitter.com/syuhu_Ako3/status/1469274434326302721/photo/1

This can be a problem for private accounts or accounts which do not wish to be discovered on Twitter. I am suggesting that when `signature: false` is set, these links to not appear.

**Comment by robertoszek** [comment]
Good catch! It makes sense we should remove those links (even by default)

The issue is that they are part of the tweet's text body as far as Twitter's API is concerned, and the entities related to images don't align perfectly when it comes to the target links.

We could do a blanket regex to match this pattern and remove them from the tweet's text, I guess.

**Comment by robertoszek** [comment]
Hi!
I've done a first implementation and wrote some tests, looks good so far but I may have missed some edgecase I didn't account for.

It will be rolled into the next stable version once I test it some more. It may take a while to publish a new version, partly because I'd rather have migrated everything to Twitter's API v2 by then.

If it's something you need right now, feel free to give the release candidate a spin installing it like this:
```
 pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple pleroma-bot==0.8.9rc4
```
And if you find some edgecase where it breaks, that would be helpful too!

By default it will remove Twitter's video and image links, you can revert to the previous behavior by setting `keep_media_links` to `true` in the config (the documentation regarding that is still pending).

**Comment by Cknight70** [comment]
Thank you! it works and I'll report if there is any issues with it. Thanks for the cool bot.

**Comment by robertoszek** [comment]
Hey @Cknight70, so far I found no issues with it on my testing. I just wanted to let you know the change is officially out with [v1.0.0](https://github.com/robertoszek/pleroma-bot/tree/1.0.0).

Please feel free to open a new issue if you end up encountering any problems with the implementation!

**Comment by Cknight70** [comment]
No issues with me! It's been working well posting multiple times a day.

**Comment by Cknight70** [comment]
@robertoszek Hey I think I did find an issue. When I retweeted something on twitter, pleroma bot did not include the picture

**Comment by Cknight70** [comment]
I'm still using the initial version, before 1.0 if changes have been made since then I'll test them out first.

**Comment by robertoszek** [comment]
@Cknight70 yeah, some issues with RTs were fixed on the latest version. Please check if it happens when using 1.0.1 too.

**Comment by robertoszek** [comment]
Hey @Cknight70 !
If you encountered any issues with how the RTs behaved with 1.0.1 (or the latest 1.0.2), feel free to open a new issue to keep track of it.
Have a nice day!
