### ISSUE TITLE
add a way to set the "bot" attribute automatically

### ISSUE THREAD

**Issue by us3r1d** [robertoszek/pleroma-bot#96]
"bot" appears to be an attribute of the account (judging from the Mastodon docs at https://docs.joinmastodon.org/entities/Account/#bot, I don't know about Pleroma).

I do know adding it to pleroma-bot's "fields" config doesn't work.  :-)

Can you add a per-account setting to the .yml file to set the bot attribute?

Thanks,
-robin

**Comment by robertoszek** [comment]
Sure thing, it makes sense to add this option letting you set the flag on each user (or globally for all users on your config).
In Mastodon there's the [/update_credentials](https://docs.joinmastodon.org/methods/accounts/#update_credentials) endpoint that lets you set the bot flag.
Pleroma's API is the mostly the same [with extra fields](https://docs-develop.pleroma.social/backend/development/API/differences_in_mastoapi_responses/#patch-apiv1accountsupdate_credentials).
I need to check how Misskey does it.

I'm thinking that when we get the profile info from the Fedi account we can check if the bot flag differs from the one defined on your .yml config, and only update it then (instead of setting it every run).

I'll look into it, thanks for the suggestion!

**Comment by robertoszek** [comment]
Ah, Misskey's endpoint is [i/update](https://misskey.io/api-doc#operation/i/update) and the field is called `isBot`. Adding it here as a note so I don't forget.

**Comment by us3r1d** [comment]
That was a remarkably fast response; thank you very much.  This will help a lot.

And now that I'm moving onto an rc release I'll get all the crash fixes I've seen you making for issues that have been glitching on my install too.  :-)

Thanks,
-robin

**Comment by robertoszek** [comment]
No problem!

You may also find some new crashes on the rc release as it's bound to be less extensively tested than the stable release 😅 
Don't hesitate to open a new issue if you run into any problems with it.

You can also check what's new on the rc release by going to the "Unreleased" section on the changelog of the develop branch:
https://github.com/robertoszek/pleroma-bot/blob/develop/CHANGELOG.md
